// Code generated by command: go run src.go -out ../../f1600x8_amd64.s -stubs ../../f1600x8stubs_amd64.go -pkg keccakf1600. DO NOT EDIT.

//go:build amd64 && !purego

package keccakf1600

//go:noescape
func f1600x8AVX512(state *uint64, rc *[24]uint64, turbo bool)
