// Code generated by command: go run src.go -out ../../f1600x8_amd64.s -stubs ../../f1600x8stubs_amd64.go -pkg keccakf1600. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func f1600x8AVX512(state *uint64, rc *[24]uint64, turbo bool)
// Requires: AVX512F
TEXT ·f1600x8AVX512(SB), NOSPLIT, $0-17
	MOVQ    state+0(FP), AX
	MOVQ    rc+8(FP), CX
	MOVQ    $0x0000000000000006, DX
	MOVBQZX turbo+16(FP), BX
	TESTQ   BX, BX
	JZ      loop
	MOVQ    $0x0000000000000003, DX
	ADDQ    $0x60, CX

loop:
	VMOVDQA64    (AX), Z0
	VMOVDQA64    64(AX), Z1
	VMOVDQA64    128(AX), Z2
	VMOVDQA64    192(AX), Z3
	VMOVDQA64    256(AX), Z4
	VPXORQ       320(AX), Z0, Z0
	VPXORQ       384(AX), Z1, Z1
	VPXORQ       448(AX), Z2, Z2
	VPXORQ       512(AX), Z3, Z3
	VPXORQ       576(AX), Z4, Z4
	VPXORQ       640(AX), Z0, Z0
	VPXORQ       704(AX), Z1, Z1
	VPXORQ       768(AX), Z2, Z2
	VPXORQ       832(AX), Z3, Z3
	VPXORQ       896(AX), Z4, Z4
	VPXORQ       960(AX), Z0, Z0
	VPXORQ       1024(AX), Z1, Z1
	VPXORQ       1088(AX), Z2, Z2
	VPXORQ       1152(AX), Z3, Z3
	VPXORQ       1216(AX), Z4, Z4
	VPXORQ       1280(AX), Z0, Z0
	VPXORQ       1344(AX), Z1, Z1
	VPXORQ       1408(AX), Z2, Z2
	VPXORQ       1472(AX), Z3, Z3
	VPXORQ       1536(AX), Z4, Z4
	VPSLLQ       $0x01, Z1, Z5
	VPSLLQ       $0x01, Z2, Z6
	VPSLLQ       $0x01, Z3, Z7
	VPSLLQ       $0x01, Z4, Z8
	VPSLLQ       $0x01, Z0, Z9
	VPSRLQ       $0x3f, Z1, Z10
	VPSRLQ       $0x3f, Z2, Z11
	VPSRLQ       $0x3f, Z3, Z12
	VPSRLQ       $0x3f, Z4, Z13
	VPSRLQ       $0x3f, Z0, Z14
	VPORQ        Z5, Z10, Z10
	VPORQ        Z6, Z11, Z11
	VPORQ        Z7, Z12, Z12
	VPORQ        Z8, Z13, Z13
	VPORQ        Z9, Z14, Z14
	VPXORQ       Z10, Z4, Z10
	VPXORQ       Z11, Z0, Z11
	VPXORQ       Z12, Z1, Z12
	VPXORQ       Z13, Z2, Z13
	VPXORQ       Z14, Z3, Z14
	VPXORQ       (AX), Z10, Z0
	VPXORQ       384(AX), Z11, Z1
	VPXORQ       768(AX), Z12, Z2
	VPXORQ       1152(AX), Z13, Z3
	VPXORQ       1536(AX), Z14, Z4
	VPSLLQ       $0x2c, Z1, Z6
	VPSLLQ       $0x2b, Z2, Z7
	VPSLLQ       $0x15, Z3, Z8
	VPSLLQ       $0x0e, Z4, Z9
	VPSRLQ       $0x14, Z1, Z1
	VPSRLQ       $0x15, Z2, Z2
	VPSRLQ       $0x2b, Z3, Z3
	VPSRLQ       $0x32, Z4, Z4
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VPBROADCASTQ (CX), Z0
	VPXORQ       Z0, Z5, Z5
	VMOVDQA64    Z5, (AX)
	VMOVDQA64    Z6, 384(AX)
	VMOVDQA64    Z7, 768(AX)
	VMOVDQA64    Z8, 1152(AX)
	VMOVDQA64    Z9, 1536(AX)
	VPXORQ       192(AX), Z13, Z0
	VPXORQ       576(AX), Z14, Z1
	VPXORQ       640(AX), Z10, Z2
	VPXORQ       1024(AX), Z11, Z3
	VPXORQ       1408(AX), Z12, Z4
	VPSLLQ       $0x1c, Z0, Z5
	VPSLLQ       $0x14, Z1, Z6
	VPSLLQ       $0x03, Z2, Z7
	VPSLLQ       $0x2d, Z3, Z8
	VPSLLQ       $0x3d, Z4, Z9
	VPSRLQ       $0x24, Z0, Z0
	VPSRLQ       $0x2c, Z1, Z1
	VPSRLQ       $0x3d, Z2, Z2
	VPSRLQ       $0x13, Z3, Z3
	VPSRLQ       $0x03, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 640(AX)
	VMOVDQA64    Z6, 1024(AX)
	VMOVDQA64    Z7, 1408(AX)
	VMOVDQA64    Z8, 192(AX)
	VMOVDQA64    Z9, 576(AX)
	VPXORQ       64(AX), Z11, Z0
	VPXORQ       448(AX), Z12, Z1
	VPXORQ       832(AX), Z13, Z2
	VPXORQ       1216(AX), Z14, Z3
	VPXORQ       1280(AX), Z10, Z4
	VPSLLQ       $0x01, Z0, Z5
	VPSLLQ       $0x06, Z1, Z6
	VPSLLQ       $0x19, Z2, Z7
	VPSLLQ       $0x08, Z3, Z8
	VPSLLQ       $0x12, Z4, Z9
	VPSRLQ       $0x3f, Z0, Z0
	VPSRLQ       $0x3a, Z1, Z1
	VPSRLQ       $0x27, Z2, Z2
	VPSRLQ       $0x38, Z3, Z3
	VPSRLQ       $0x2e, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 1280(AX)
	VMOVDQA64    Z6, 64(AX)
	VMOVDQA64    Z7, 448(AX)
	VMOVDQA64    Z8, 832(AX)
	VMOVDQA64    Z9, 1216(AX)
	VPXORQ       256(AX), Z14, Z0
	VPXORQ       320(AX), Z10, Z1
	VPXORQ       704(AX), Z11, Z2
	VPXORQ       1088(AX), Z12, Z3
	VPXORQ       1472(AX), Z13, Z4
	VPSLLQ       $0x1b, Z0, Z5
	VPSLLQ       $0x24, Z1, Z6
	VPSLLQ       $0x0a, Z2, Z7
	VPSLLQ       $0x0f, Z3, Z8
	VPSLLQ       $0x38, Z4, Z9
	VPSRLQ       $0x25, Z0, Z0
	VPSRLQ       $0x1c, Z1, Z1
	VPSRLQ       $0x36, Z2, Z2
	VPSRLQ       $0x31, Z3, Z3
	VPSRLQ       $0x08, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 320(AX)
	VMOVDQA64    Z6, 704(AX)
	VMOVDQA64    Z7, 1088(AX)
	VMOVDQA64    Z8, 1472(AX)
	VMOVDQA64    Z9, 256(AX)
	VPXORQ       128(AX), Z12, Z0
	VPXORQ       512(AX), Z13, Z1
	VPXORQ       896(AX), Z14, Z2
	VPXORQ       960(AX), Z10, Z3
	VPXORQ       1344(AX), Z11, Z4
	VPSLLQ       $0x3e, Z0, Z5
	VPSLLQ       $0x37, Z1, Z6
	VPSLLQ       $0x27, Z2, Z7
	VPSLLQ       $0x29, Z3, Z8
	VPSLLQ       $0x02, Z4, Z9
	VPSRLQ       $0x02, Z0, Z0
	VPSRLQ       $0x09, Z1, Z1
	VPSRLQ       $0x19, Z2, Z2
	VPSRLQ       $0x17, Z3, Z3
	VPSRLQ       $0x3e, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 960(AX)
	VMOVDQA64    Z6, 1344(AX)
	VMOVDQA64    Z7, 128(AX)
	VMOVDQA64    Z8, 512(AX)
	VMOVDQA64    Z9, 896(AX)
	VMOVDQA64    (AX), Z0
	VMOVDQA64    64(AX), Z1
	VMOVDQA64    128(AX), Z2
	VMOVDQA64    192(AX), Z3
	VMOVDQA64    256(AX), Z4
	VPXORQ       320(AX), Z0, Z0
	VPXORQ       384(AX), Z1, Z1
	VPXORQ       448(AX), Z2, Z2
	VPXORQ       512(AX), Z3, Z3
	VPXORQ       576(AX), Z4, Z4
	VPXORQ       640(AX), Z0, Z0
	VPXORQ       704(AX), Z1, Z1
	VPXORQ       768(AX), Z2, Z2
	VPXORQ       832(AX), Z3, Z3
	VPXORQ       896(AX), Z4, Z4
	VPXORQ       960(AX), Z0, Z0
	VPXORQ       1024(AX), Z1, Z1
	VPXORQ       1088(AX), Z2, Z2
	VPXORQ       1152(AX), Z3, Z3
	VPXORQ       1216(AX), Z4, Z4
	VPXORQ       1280(AX), Z0, Z0
	VPXORQ       1344(AX), Z1, Z1
	VPXORQ       1408(AX), Z2, Z2
	VPXORQ       1472(AX), Z3, Z3
	VPXORQ       1536(AX), Z4, Z4
	VPSLLQ       $0x01, Z1, Z5
	VPSLLQ       $0x01, Z2, Z6
	VPSLLQ       $0x01, Z3, Z7
	VPSLLQ       $0x01, Z4, Z8
	VPSLLQ       $0x01, Z0, Z9
	VPSRLQ       $0x3f, Z1, Z10
	VPSRLQ       $0x3f, Z2, Z11
	VPSRLQ       $0x3f, Z3, Z12
	VPSRLQ       $0x3f, Z4, Z13
	VPSRLQ       $0x3f, Z0, Z14
	VPORQ        Z5, Z10, Z10
	VPORQ        Z6, Z11, Z11
	VPORQ        Z7, Z12, Z12
	VPORQ        Z8, Z13, Z13
	VPORQ        Z9, Z14, Z14
	VPXORQ       Z10, Z4, Z10
	VPXORQ       Z11, Z0, Z11
	VPXORQ       Z12, Z1, Z12
	VPXORQ       Z13, Z2, Z13
	VPXORQ       Z14, Z3, Z14
	VPXORQ       (AX), Z10, Z0
	VPXORQ       1024(AX), Z11, Z1
	VPXORQ       448(AX), Z12, Z2
	VPXORQ       1472(AX), Z13, Z3
	VPXORQ       896(AX), Z14, Z4
	VPSLLQ       $0x2c, Z1, Z6
	VPSLLQ       $0x2b, Z2, Z7
	VPSLLQ       $0x15, Z3, Z8
	VPSLLQ       $0x0e, Z4, Z9
	VPSRLQ       $0x14, Z1, Z1
	VPSRLQ       $0x15, Z2, Z2
	VPSRLQ       $0x2b, Z3, Z3
	VPSRLQ       $0x32, Z4, Z4
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VPBROADCASTQ 8(CX), Z0
	VPXORQ       Z0, Z5, Z5
	VMOVDQA64    Z5, (AX)
	VMOVDQA64    Z6, 1024(AX)
	VMOVDQA64    Z7, 448(AX)
	VMOVDQA64    Z8, 1472(AX)
	VMOVDQA64    Z9, 896(AX)
	VPXORQ       1152(AX), Z13, Z0
	VPXORQ       576(AX), Z14, Z1
	VPXORQ       1280(AX), Z10, Z2
	VPXORQ       704(AX), Z11, Z3
	VPXORQ       128(AX), Z12, Z4
	VPSLLQ       $0x1c, Z0, Z5
	VPSLLQ       $0x14, Z1, Z6
	VPSLLQ       $0x03, Z2, Z7
	VPSLLQ       $0x2d, Z3, Z8
	VPSLLQ       $0x3d, Z4, Z9
	VPSRLQ       $0x24, Z0, Z0
	VPSRLQ       $0x2c, Z1, Z1
	VPSRLQ       $0x3d, Z2, Z2
	VPSRLQ       $0x13, Z3, Z3
	VPSRLQ       $0x03, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 1280(AX)
	VMOVDQA64    Z6, 704(AX)
	VMOVDQA64    Z7, 128(AX)
	VMOVDQA64    Z8, 1152(AX)
	VMOVDQA64    Z9, 576(AX)
	VPXORQ       384(AX), Z11, Z0
	VPXORQ       1408(AX), Z12, Z1
	VPXORQ       832(AX), Z13, Z2
	VPXORQ       256(AX), Z14, Z3
	VPXORQ       960(AX), Z10, Z4
	VPSLLQ       $0x01, Z0, Z5
	VPSLLQ       $0x06, Z1, Z6
	VPSLLQ       $0x19, Z2, Z7
	VPSLLQ       $0x08, Z3, Z8
	VPSLLQ       $0x12, Z4, Z9
	VPSRLQ       $0x3f, Z0, Z0
	VPSRLQ       $0x3a, Z1, Z1
	VPSRLQ       $0x27, Z2, Z2
	VPSRLQ       $0x38, Z3, Z3
	VPSRLQ       $0x2e, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 960(AX)
	VMOVDQA64    Z6, 384(AX)
	VMOVDQA64    Z7, 1408(AX)
	VMOVDQA64    Z8, 832(AX)
	VMOVDQA64    Z9, 256(AX)
	VPXORQ       1536(AX), Z14, Z0
	VPXORQ       640(AX), Z10, Z1
	VPXORQ       64(AX), Z11, Z2
	VPXORQ       1088(AX), Z12, Z3
	VPXORQ       512(AX), Z13, Z4
	VPSLLQ       $0x1b, Z0, Z5
	VPSLLQ       $0x24, Z1, Z6
	VPSLLQ       $0x0a, Z2, Z7
	VPSLLQ       $0x0f, Z3, Z8
	VPSLLQ       $0x38, Z4, Z9
	VPSRLQ       $0x25, Z0, Z0
	VPSRLQ       $0x1c, Z1, Z1
	VPSRLQ       $0x36, Z2, Z2
	VPSRLQ       $0x31, Z3, Z3
	VPSRLQ       $0x08, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 640(AX)
	VMOVDQA64    Z6, 64(AX)
	VMOVDQA64    Z7, 1088(AX)
	VMOVDQA64    Z8, 512(AX)
	VMOVDQA64    Z9, 1536(AX)
	VPXORQ       768(AX), Z12, Z0
	VPXORQ       192(AX), Z13, Z1
	VPXORQ       1216(AX), Z14, Z2
	VPXORQ       320(AX), Z10, Z3
	VPXORQ       1344(AX), Z11, Z4
	VPSLLQ       $0x3e, Z0, Z5
	VPSLLQ       $0x37, Z1, Z6
	VPSLLQ       $0x27, Z2, Z7
	VPSLLQ       $0x29, Z3, Z8
	VPSLLQ       $0x02, Z4, Z9
	VPSRLQ       $0x02, Z0, Z0
	VPSRLQ       $0x09, Z1, Z1
	VPSRLQ       $0x19, Z2, Z2
	VPSRLQ       $0x17, Z3, Z3
	VPSRLQ       $0x3e, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 320(AX)
	VMOVDQA64    Z6, 1344(AX)
	VMOVDQA64    Z7, 768(AX)
	VMOVDQA64    Z8, 192(AX)
	VMOVDQA64    Z9, 1216(AX)
	VMOVDQA64    (AX), Z0
	VMOVDQA64    64(AX), Z1
	VMOVDQA64    128(AX), Z2
	VMOVDQA64    192(AX), Z3
	VMOVDQA64    256(AX), Z4
	VPXORQ       320(AX), Z0, Z0
	VPXORQ       384(AX), Z1, Z1
	VPXORQ       448(AX), Z2, Z2
	VPXORQ       512(AX), Z3, Z3
	VPXORQ       576(AX), Z4, Z4
	VPXORQ       640(AX), Z0, Z0
	VPXORQ       704(AX), Z1, Z1
	VPXORQ       768(AX), Z2, Z2
	VPXORQ       832(AX), Z3, Z3
	VPXORQ       896(AX), Z4, Z4
	VPXORQ       960(AX), Z0, Z0
	VPXORQ       1024(AX), Z1, Z1
	VPXORQ       1088(AX), Z2, Z2
	VPXORQ       1152(AX), Z3, Z3
	VPXORQ       1216(AX), Z4, Z4
	VPXORQ       1280(AX), Z0, Z0
	VPXORQ       1344(AX), Z1, Z1
	VPXORQ       1408(AX), Z2, Z2
	VPXORQ       1472(AX), Z3, Z3
	VPXORQ       1536(AX), Z4, Z4
	VPSLLQ       $0x01, Z1, Z5
	VPSLLQ       $0x01, Z2, Z6
	VPSLLQ       $0x01, Z3, Z7
	VPSLLQ       $0x01, Z4, Z8
	VPSLLQ       $0x01, Z0, Z9
	VPSRLQ       $0x3f, Z1, Z10
	VPSRLQ       $0x3f, Z2, Z11
	VPSRLQ       $0x3f, Z3, Z12
	VPSRLQ       $0x3f, Z4, Z13
	VPSRLQ       $0x3f, Z0, Z14
	VPORQ        Z5, Z10, Z10
	VPORQ        Z6, Z11, Z11
	VPORQ        Z7, Z12, Z12
	VPORQ        Z8, Z13, Z13
	VPORQ        Z9, Z14, Z14
	VPXORQ       Z10, Z4, Z10
	VPXORQ       Z11, Z0, Z11
	VPXORQ       Z12, Z1, Z12
	VPXORQ       Z13, Z2, Z13
	VPXORQ       Z14, Z3, Z14
	VPXORQ       (AX), Z10, Z0
	VPXORQ       704(AX), Z11, Z1
	VPXORQ       1408(AX), Z12, Z2
	VPXORQ       512(AX), Z13, Z3
	VPXORQ       1216(AX), Z14, Z4
	VPSLLQ       $0x2c, Z1, Z6
	VPSLLQ       $0x2b, Z2, Z7
	VPSLLQ       $0x15, Z3, Z8
	VPSLLQ       $0x0e, Z4, Z9
	VPSRLQ       $0x14, Z1, Z1
	VPSRLQ       $0x15, Z2, Z2
	VPSRLQ       $0x2b, Z3, Z3
	VPSRLQ       $0x32, Z4, Z4
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VPBROADCASTQ 16(CX), Z0
	VPXORQ       Z0, Z5, Z5
	VMOVDQA64    Z5, (AX)
	VMOVDQA64    Z6, 704(AX)
	VMOVDQA64    Z7, 1408(AX)
	VMOVDQA64    Z8, 512(AX)
	VMOVDQA64    Z9, 1216(AX)
	VPXORQ       1472(AX), Z13, Z0
	VPXORQ       576(AX), Z14, Z1
	VPXORQ       960(AX), Z10, Z2
	VPXORQ       64(AX), Z11, Z3
	VPXORQ       768(AX), Z12, Z4
	VPSLLQ       $0x1c, Z0, Z5
	VPSLLQ       $0x14, Z1, Z6
	VPSLLQ       $0x03, Z2, Z7
	VPSLLQ       $0x2d, Z3, Z8
	VPSLLQ       $0x3d, Z4, Z9
	VPSRLQ       $0x24, Z0, Z0
	VPSRLQ       $0x2c, Z1, Z1
	VPSRLQ       $0x3d, Z2, Z2
	VPSRLQ       $0x13, Z3, Z3
	VPSRLQ       $0x03, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 960(AX)
	VMOVDQA64    Z6, 64(AX)
	VMOVDQA64    Z7, 768(AX)
	VMOVDQA64    Z8, 1472(AX)
	VMOVDQA64    Z9, 576(AX)
	VPXORQ       1024(AX), Z11, Z0
	VPXORQ       128(AX), Z12, Z1
	VPXORQ       832(AX), Z13, Z2
	VPXORQ       1536(AX), Z14, Z3
	VPXORQ       320(AX), Z10, Z4
	VPSLLQ       $0x01, Z0, Z5
	VPSLLQ       $0x06, Z1, Z6
	VPSLLQ       $0x19, Z2, Z7
	VPSLLQ       $0x08, Z3, Z8
	VPSLLQ       $0x12, Z4, Z9
	VPSRLQ       $0x3f, Z0, Z0
	VPSRLQ       $0x3a, Z1, Z1
	VPSRLQ       $0x27, Z2, Z2
	VPSRLQ       $0x38, Z3, Z3
	VPSRLQ       $0x2e, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 320(AX)
	VMOVDQA64    Z6, 1024(AX)
	VMOVDQA64    Z7, 128(AX)
	VMOVDQA64    Z8, 832(AX)
	VMOVDQA64    Z9, 1536(AX)
	VPXORQ       896(AX), Z14, Z0
	VPXORQ       1280(AX), Z10, Z1
	VPXORQ       384(AX), Z11, Z2
	VPXORQ       1088(AX), Z12, Z3
	VPXORQ       192(AX), Z13, Z4
	VPSLLQ       $0x1b, Z0, Z5
	VPSLLQ       $0x24, Z1, Z6
	VPSLLQ       $0x0a, Z2, Z7
	VPSLLQ       $0x0f, Z3, Z8
	VPSLLQ       $0x38, Z4, Z9
	VPSRLQ       $0x25, Z0, Z0
	VPSRLQ       $0x1c, Z1, Z1
	VPSRLQ       $0x36, Z2, Z2
	VPSRLQ       $0x31, Z3, Z3
	VPSRLQ       $0x08, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 1280(AX)
	VMOVDQA64    Z6, 384(AX)
	VMOVDQA64    Z7, 1088(AX)
	VMOVDQA64    Z8, 192(AX)
	VMOVDQA64    Z9, 896(AX)
	VPXORQ       448(AX), Z12, Z0
	VPXORQ       1152(AX), Z13, Z1
	VPXORQ       256(AX), Z14, Z2
	VPXORQ       640(AX), Z10, Z3
	VPXORQ       1344(AX), Z11, Z4
	VPSLLQ       $0x3e, Z0, Z5
	VPSLLQ       $0x37, Z1, Z6
	VPSLLQ       $0x27, Z2, Z7
	VPSLLQ       $0x29, Z3, Z8
	VPSLLQ       $0x02, Z4, Z9
	VPSRLQ       $0x02, Z0, Z0
	VPSRLQ       $0x09, Z1, Z1
	VPSRLQ       $0x19, Z2, Z2
	VPSRLQ       $0x17, Z3, Z3
	VPSRLQ       $0x3e, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 640(AX)
	VMOVDQA64    Z6, 1344(AX)
	VMOVDQA64    Z7, 448(AX)
	VMOVDQA64    Z8, 1152(AX)
	VMOVDQA64    Z9, 256(AX)
	VMOVDQA64    (AX), Z0
	VMOVDQA64    64(AX), Z1
	VMOVDQA64    128(AX), Z2
	VMOVDQA64    192(AX), Z3
	VMOVDQA64    256(AX), Z4
	VPXORQ       320(AX), Z0, Z0
	VPXORQ       384(AX), Z1, Z1
	VPXORQ       448(AX), Z2, Z2
	VPXORQ       512(AX), Z3, Z3
	VPXORQ       576(AX), Z4, Z4
	VPXORQ       640(AX), Z0, Z0
	VPXORQ       704(AX), Z1, Z1
	VPXORQ       768(AX), Z2, Z2
	VPXORQ       832(AX), Z3, Z3
	VPXORQ       896(AX), Z4, Z4
	VPXORQ       960(AX), Z0, Z0
	VPXORQ       1024(AX), Z1, Z1
	VPXORQ       1088(AX), Z2, Z2
	VPXORQ       1152(AX), Z3, Z3
	VPXORQ       1216(AX), Z4, Z4
	VPXORQ       1280(AX), Z0, Z0
	VPXORQ       1344(AX), Z1, Z1
	VPXORQ       1408(AX), Z2, Z2
	VPXORQ       1472(AX), Z3, Z3
	VPXORQ       1536(AX), Z4, Z4
	VPSLLQ       $0x01, Z1, Z5
	VPSLLQ       $0x01, Z2, Z6
	VPSLLQ       $0x01, Z3, Z7
	VPSLLQ       $0x01, Z4, Z8
	VPSLLQ       $0x01, Z0, Z9
	VPSRLQ       $0x3f, Z1, Z10
	VPSRLQ       $0x3f, Z2, Z11
	VPSRLQ       $0x3f, Z3, Z12
	VPSRLQ       $0x3f, Z4, Z13
	VPSRLQ       $0x3f, Z0, Z14
	VPORQ        Z5, Z10, Z10
	VPORQ        Z6, Z11, Z11
	VPORQ        Z7, Z12, Z12
	VPORQ        Z8, Z13, Z13
	VPORQ        Z9, Z14, Z14
	VPXORQ       Z10, Z4, Z10
	VPXORQ       Z11, Z0, Z11
	VPXORQ       Z12, Z1, Z12
	VPXORQ       Z13, Z2, Z13
	VPXORQ       Z14, Z3, Z14
	VPXORQ       (AX), Z10, Z0
	VPXORQ       64(AX), Z11, Z1
	VPXORQ       128(AX), Z12, Z2
	VPXORQ       192(AX), Z13, Z3
	VPXORQ       256(AX), Z14, Z4
	VPSLLQ       $0x2c, Z1, Z6
	VPSLLQ       $0x2b, Z2, Z7
	VPSLLQ       $0x15, Z3, Z8
	VPSLLQ       $0x0e, Z4, Z9
	VPSRLQ       $0x14, Z1, Z1
	VPSRLQ       $0x15, Z2, Z2
	VPSRLQ       $0x2b, Z3, Z3
	VPSRLQ       $0x32, Z4, Z4
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VPBROADCASTQ 24(CX), Z0
	VPXORQ       Z0, Z5, Z5
	VMOVDQA64    Z5, (AX)
	VMOVDQA64    Z6, 64(AX)
	VMOVDQA64    Z7, 128(AX)
	VMOVDQA64    Z8, 192(AX)
	VMOVDQA64    Z9, 256(AX)
	VPXORQ       512(AX), Z13, Z0
	VPXORQ       576(AX), Z14, Z1
	VPXORQ       320(AX), Z10, Z2
	VPXORQ       384(AX), Z11, Z3
	VPXORQ       448(AX), Z12, Z4
	VPSLLQ       $0x1c, Z0, Z5
	VPSLLQ       $0x14, Z1, Z6
	VPSLLQ       $0x03, Z2, Z7
	VPSLLQ       $0x2d, Z3, Z8
	VPSLLQ       $0x3d, Z4, Z9
	VPSRLQ       $0x24, Z0, Z0
	VPSRLQ       $0x2c, Z1, Z1
	VPSRLQ       $0x3d, Z2, Z2
	VPSRLQ       $0x13, Z3, Z3
	VPSRLQ       $0x03, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 320(AX)
	VMOVDQA64    Z6, 384(AX)
	VMOVDQA64    Z7, 448(AX)
	VMOVDQA64    Z8, 512(AX)
	VMOVDQA64    Z9, 576(AX)
	VPXORQ       704(AX), Z11, Z0
	VPXORQ       768(AX), Z12, Z1
	VPXORQ       832(AX), Z13, Z2
	VPXORQ       896(AX), Z14, Z3
	VPXORQ       640(AX), Z10, Z4
	VPSLLQ       $0x01, Z0, Z5
	VPSLLQ       $0x06, Z1, Z6
	VPSLLQ       $0x19, Z2, Z7
	VPSLLQ       $0x08, Z3, Z8
	VPSLLQ       $0x12, Z4, Z9
	VPSRLQ       $0x3f, Z0, Z0
	VPSRLQ       $0x3a, Z1, Z1
	VPSRLQ       $0x27, Z2, Z2
	VPSRLQ       $0x38, Z3, Z3
	VPSRLQ       $0x2e, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 640(AX)
	VMOVDQA64    Z6, 704(AX)
	VMOVDQA64    Z7, 768(AX)
	VMOVDQA64    Z8, 832(AX)
	VMOVDQA64    Z9, 896(AX)
	VPXORQ       1216(AX), Z14, Z0
	VPXORQ       960(AX), Z10, Z1
	VPXORQ       1024(AX), Z11, Z2
	VPXORQ       1088(AX), Z12, Z3
	VPXORQ       1152(AX), Z13, Z4
	VPSLLQ       $0x1b, Z0, Z5
	VPSLLQ       $0x24, Z1, Z6
	VPSLLQ       $0x0a, Z2, Z7
	VPSLLQ       $0x0f, Z3, Z8
	VPSLLQ       $0x38, Z4, Z9
	VPSRLQ       $0x25, Z0, Z0
	VPSRLQ       $0x1c, Z1, Z1
	VPSRLQ       $0x36, Z2, Z2
	VPSRLQ       $0x31, Z3, Z3
	VPSRLQ       $0x08, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 960(AX)
	VMOVDQA64    Z6, 1024(AX)
	VMOVDQA64    Z7, 1088(AX)
	VMOVDQA64    Z8, 1152(AX)
	VMOVDQA64    Z9, 1216(AX)
	VPXORQ       1408(AX), Z12, Z0
	VPXORQ       1472(AX), Z13, Z1
	VPXORQ       1536(AX), Z14, Z2
	VPXORQ       1280(AX), Z10, Z3
	VPXORQ       1344(AX), Z11, Z4
	VPSLLQ       $0x3e, Z0, Z5
	VPSLLQ       $0x37, Z1, Z6
	VPSLLQ       $0x27, Z2, Z7
	VPSLLQ       $0x29, Z3, Z8
	VPSLLQ       $0x02, Z4, Z9
	VPSRLQ       $0x02, Z0, Z0
	VPSRLQ       $0x09, Z1, Z1
	VPSRLQ       $0x19, Z2, Z2
	VPSRLQ       $0x17, Z3, Z3
	VPSRLQ       $0x3e, Z4, Z4
	VPORQ        Z5, Z0, Z0
	VPORQ        Z6, Z1, Z1
	VPORQ        Z7, Z2, Z2
	VPORQ        Z8, Z3, Z3
	VPORQ        Z9, Z4, Z4
	VPANDNQ      Z2, Z1, Z5
	VPANDNQ      Z3, Z2, Z6
	VPANDNQ      Z4, Z3, Z7
	VPANDNQ      Z0, Z4, Z8
	VPANDNQ      Z1, Z0, Z9
	VPXORQ       Z0, Z5, Z5
	VPXORQ       Z1, Z6, Z6
	VPXORQ       Z2, Z7, Z7
	VPXORQ       Z3, Z8, Z8
	VPXORQ       Z4, Z9, Z9
	VMOVDQA64    Z5, 1280(AX)
	VMOVDQA64    Z6, 1344(AX)
	VMOVDQA64    Z7, 1408(AX)
	VMOVDQA64    Z8, 1472(AX)
	VMOVDQA64    Z9, 1536(AX)
	ADDQ         $0x20, CX
	SUBQ         $0x00000001, DX
	JNZ          loop
	RET
